### ISSUE TITLE
Uses python 2, which is EOL

### ISSUE THREAD

**Issue by bmulholland** [Araxeus/gitify#3]
Fails because macos no longer has python2:

```
$ electron-builder --mac --universal
  • electron-builder  version=22.14.13 os=21.5.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=17.1.2 appOutDir=dist/mac-universal--x64
  • packaging       platform=darwin arch=arm64 electron=17.1.2 appOutDir=dist/mac-universal--arm64
  • packaging       platform=darwin arch=universal electron=17.1.2 appOutDir=dist/mac-universal
  • skipped macOS application code signing  reason=Identity name is specified, but no valid identity with this name in the keychain identity=Emmanouil Konstantinidis (3YP8SXP3BF) allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found
  • notarizing      either should not notarize or not building for macOS
  • building        target=macOS zip arch=universal file=dist/Gitify-4.3.2-universal-mac.zip
  • building        target=DMG arch=universal file=dist/Gitify-4.3.2-universal.dmg
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • building block map  blockMapFile=dist/Gitify-4.3.2-universal-mac.zip.blockmap
  ⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
    at /Users/bmulholland/sources/gitify/node_modules/builder-util/src/util.ts:133:18
    at exithandler (node:child_process:397:5)
    at ChildProcess.errorhandler (node:child_process:409:5)
    at ChildProcess.emit (node:events:537:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
error Command failed with exit code 1.
```

**Comment by bmulholland** [comment]
The main issue seems to be that all the dependencies are very out of date

**Comment by bmulholland** [comment]
I tried updating all the dependencies but there's breaking changes. I think we'll need to upgrade each package one at a time. What do you think about enabling dependabot and working through those one by one?

**Comment by Araxeus** [comment]
can you try updating only electron-builder and see if that helps?

alternatively couldn't you just install python?

**Comment by bmulholland** [comment]
Yes, I suppose I could install python2. It's been EOL'd, though, and upgrading dependencies to get python3 support seems like the better way?

**Comment by bmulholland** [comment]
Okay strange: I had it working at one point, and pretty sure I just upgraded electron-builder for that. But I wiped that out to see if it was still necessary, and now I can't get to a working state (without python2) again.

**Comment by Araxeus** [comment]
updating electron-builder to atleast 23.0.2 should fix this according to this issue https://github.com/electron-userland/electron-builder/issues/6606#issuecomment-1062436795

are you sure that it doesn't work if you update only electron-builder in the custom-release branch?

can you just run `yarn add electron-builder` to make sure that its updated to the latest version?

**Comment by bmulholland** [comment]
Yeah the problem was that I just did `yarn upgrade` without changing `package.json`. Whoops :). Back to working again with electron-builder 23.1.0
